version: "3.7"
services:
  cc_server:
    build: .
    container_name: cc_server
    # restart: unless-stopped
    env_file: .env
    volumes:
      - .:/cc_server:cached
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - container_network
    depends_on:
      - cc_mysql
      - ccredis
  cc_mysql:
    container_name: cc_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - 3306
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d/
      - ./db/data/MySQL/:/var/lib/mysql/
    networks:
      - container_network
  ccredis:
    container_name: ccredis
    image: redis:latest
    command: redis-server --requirepass $REDIS_PASSWORD --bind ccredis --port 6379
    env_file: .env
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - 6379
    volumes:
      - ./db/data/Redis:/data
    networks:
      - container_network
networks:
  container_network:
    driver: bridge